name: Bug Fix
description: Fix a bug with clear reproduction, scope, and tests
title: "[BUG FIX] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing a bug fix! Please complete the sections below so reviewers can understand and verify the change quickly.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What bug is fixed and what parts of the codebase are impacted?
      placeholder: Resolves incorrect behaviour or crash in a kernel (e.g. copy, swap, axpby, ...) or test/benchmark...
    validations:
      required: true
  - type: textarea
    id: root-cause
    attributes:
      label: Root cause
      description: Briefly describe the underlying issue.
      placeholder: The kernel assumed a specific layout / dtype / device / size, or the benchmark/test was incorrect...
  - type: textarea
    id: changes
    attributes:
      label: Changes
      description: Highlight the notable code-level modifications.
      placeholder: Updated `omni_moe.ops.*` implementation or tests/benchmarks to...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps or MRE
      description: Provide steps or a minimal snippet that reproduces the original bug.
      render: python
  - type: textarea
    id: tests
    attributes:
      label: Tests
      description: List the tests you added or ran and their results.
      placeholder: Ran `pytest test` and relevant benchmarks in `test/testing.py`; added or updated unit tests...
    validations:
      required: true
  - type: textarea
    id: compatibility
    attributes:
      label: Compatibility
      description: Note any migration concerns or backwards compatibility considerations.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Linked issue provided
        - label: Adds or updates tests
        - label: Updates docs if needed
        - label: No performance regressions observed
